### ISSUE TITLE
Open links in new tabs

### ISSUE THREAD

**Issue by mohammadshaad** [shubhamchandak94/shubhamchandak94.github.io#14]
Your website is fantastic, however I just wanted to make a small modification so that the links open in a new tab rather than the current one. Although this may seem like a minor issue, it is crucial because it will make it simple for visitors to click on different links and return back to your website.

**Comment by mohammadshaad** [comment]
@shubhamchandak94 kindly assign me this issue.

**Comment by shubhamchandak94** [comment]
done

**Comment by shubhamchandak94** [comment]
feel free to create a PR. Thanks!

**Comment by mohammadshaad** [comment]
Thank you so much

**Comment by mohammadshaad** [comment]
@shubhamchandak94 I have made the PR kindly review and merge the PR

**Comment by shubhamchandak94** [comment]
Thanks Mohammad! I have merged the PR now. If you mind me asking, how did you come across this site and why were you interested in making this PR?
Regards,
Shubham

**Comment by mohammadshaad** [comment]
Thank you so much 
Actually I came across your website through your linkedin.
